<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use App\Migration\AbstractMultiPlatformMigration;
use Doctrine\DBAL\Schema\Schema;

final class Version20260903210000 extends AbstractMultiPlatformMigration
{
    public function getDescription(): string
    {
        return 'Add safe, versioned customer datasheet templates with layout blocks and child-electronics table mappings.';
    }

    public function mySQLUp(Schema $schema): void
    {
        $this->createTables('INT AUTO_INCREMENT NOT NULL', 'INT', 'TINYINT(1)', '1', '0', 'LONGTEXT', 'DATETIME', 'JSON', ', PRIMARY KEY(id)', 'DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
    }

    public function sqLiteUp(Schema $schema): void
    {
        $this->createTables('INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL', 'INTEGER', 'BOOLEAN', '1', '0', 'CLOB', 'DATETIME', 'CLOB', '', '');
    }

    public function postgreSQLUp(Schema $schema): void
    {
        $this->createTables('INT GENERATED BY DEFAULT AS IDENTITY NOT NULL', 'INT', 'BOOLEAN', 'TRUE', 'FALSE', 'TEXT', 'TIMESTAMP(0) WITHOUT TIME ZONE', 'JSON', ', PRIMARY KEY(id)', '');
    }

    public function mySQLDown(Schema $schema): void
    {
        $this->dropTables();
    }

    public function sqLiteDown(Schema $schema): void
    {
        $this->dropTables();
    }

    public function postgreSQLDown(Schema $schema): void
    {
        $this->dropTables();
    }

    private function createTables(string $id, string $integer, string $boolean, string $true, string $false, string $text, string $datetime, string $json, string $primaryKey, string $suffix): void
    {
        $this->addSql(sprintf('CREATE TABLE production_datasheet_templates (id %s, name VARCHAR(255) NOT NULL, product_title VARCHAR(255) NOT NULL, description %s NOT NULL, active %s DEFAULT %s NOT NULL, last_modified %s DEFAULT CURRENT_TIMESTAMP NOT NULL, datetime_added %s DEFAULT CURRENT_TIMESTAMP NOT NULL%s) %s', $id, $text, $boolean, $true, $datetime, $datetime, $primaryKey, $suffix));

        $this->addSql(sprintf('CREATE TABLE production_datasheet_template_revisions (id %s, template_id %s NOT NULL, published_by_id %s DEFAULT NULL, revision_number %s NOT NULL, status VARCHAR(24) NOT NULL, change_note VARCHAR(255) DEFAULT NULL, published_at %s DEFAULT NULL, last_modified %s DEFAULT CURRENT_TIMESTAMP NOT NULL, datetime_added %s DEFAULT CURRENT_TIMESTAMP NOT NULL%s, CONSTRAINT FK_PROD_DATASHEET_REV_TEMPLATE FOREIGN KEY (template_id) REFERENCES production_datasheet_templates (id) ON DELETE CASCADE, CONSTRAINT FK_PROD_DATASHEET_REV_USER FOREIGN KEY (published_by_id) REFERENCES users (id) ON DELETE SET NULL) %s', $id, $integer, $integer, $integer, $datetime, $datetime, $datetime, $primaryKey, $suffix));
        $this->addSql('CREATE INDEX IDX_PROD_DATASHEET_REV_TEMPLATE ON production_datasheet_template_revisions (template_id)');
        $this->addSql('CREATE INDEX IDX_PROD_DATASHEET_REV_USER ON production_datasheet_template_revisions (published_by_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROD_DATASHEET_REVISION ON production_datasheet_template_revisions (template_id, revision_number)');

        $this->addSql(sprintf('CREATE TABLE production_datasheet_template_blocks (id %s, revision_id %s NOT NULL, stable_key VARCHAR(36) NOT NULL, type VARCHAR(32) NOT NULL, label VARCHAR(255) DEFAULT NULL, text %s DEFAULT NULL, source_path VARCHAR(255) DEFAULT NULL, position %s NOT NULL, layout_columns SMALLINT DEFAULT 12 NOT NULL, start_new_row %s DEFAULT %s NOT NULL, required %s DEFAULT %s NOT NULL, hide_if_empty %s DEFAULT %s NOT NULL, minimum_rows %s DEFAULT 0 NOT NULL, maximum_rows %s DEFAULT NULL, last_modified %s DEFAULT CURRENT_TIMESTAMP NOT NULL, datetime_added %s DEFAULT CURRENT_TIMESTAMP NOT NULL%s, CONSTRAINT FK_PROD_DATASHEET_BLOCK_REV FOREIGN KEY (revision_id) REFERENCES production_datasheet_template_revisions (id) ON DELETE CASCADE) %s', $id, $integer, $text, $integer, $boolean, $false, $boolean, $false, $boolean, $false, $integer, $integer, $datetime, $datetime, $primaryKey, $suffix));
        $this->addSql('CREATE INDEX IDX_PROD_DATASHEET_BLOCK_REV ON production_datasheet_template_blocks (revision_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROD_DATASHEET_BLOCK_KEY ON production_datasheet_template_blocks (revision_id, stable_key)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROD_DATASHEET_BLOCK_POSITION ON production_datasheet_template_blocks (revision_id, position)');

        $this->addSql(sprintf('CREATE TABLE production_datasheet_table_columns (id %s, block_id %s NOT NULL, stable_key VARCHAR(36) NOT NULL, label VARCHAR(255) NOT NULL, source_path VARCHAR(255) NOT NULL, unit VARCHAR(32) DEFAULT NULL, position %s NOT NULL, required %s DEFAULT %s NOT NULL, last_modified %s DEFAULT CURRENT_TIMESTAMP NOT NULL, datetime_added %s DEFAULT CURRENT_TIMESTAMP NOT NULL%s, CONSTRAINT FK_PROD_DATASHEET_COLUMN_BLOCK FOREIGN KEY (block_id) REFERENCES production_datasheet_template_blocks (id) ON DELETE CASCADE) %s', $id, $integer, $integer, $boolean, $false, $datetime, $datetime, $primaryKey, $suffix));
        $this->addSql('CREATE INDEX IDX_PROD_DATASHEET_COLUMN_BLOCK ON production_datasheet_table_columns (block_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROD_DATASHEET_COLUMN_KEY ON production_datasheet_table_columns (block_id, stable_key)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROD_DATASHEET_COLUMN_POSITION ON production_datasheet_table_columns (block_id, position)');

        $this->addSql(sprintf('CREATE TABLE production_datasheet_documents (id %s, build_instance_id %s NOT NULL, template_id %s NOT NULL, revision_id %s NOT NULL, released_by_id %s DEFAULT NULL, document_revision %s NOT NULL, original_filename VARCHAR(255) NOT NULL, stored_filename VARCHAR(255) NOT NULL, file_size %s NOT NULL, sha256_checksum VARCHAR(64) NOT NULL, source_snapshot %s NOT NULL, released_at %s NOT NULL, last_modified %s DEFAULT CURRENT_TIMESTAMP NOT NULL, datetime_added %s DEFAULT CURRENT_TIMESTAMP NOT NULL%s, CONSTRAINT FK_PROD_DATASHEET_DOC_BUILD FOREIGN KEY (build_instance_id) REFERENCES production_build_instances (id), CONSTRAINT FK_PROD_DATASHEET_DOC_TEMPLATE FOREIGN KEY (template_id) REFERENCES production_datasheet_templates (id), CONSTRAINT FK_PROD_DATASHEET_DOC_REVISION FOREIGN KEY (revision_id) REFERENCES production_datasheet_template_revisions (id), CONSTRAINT FK_PROD_DATASHEET_DOC_USER FOREIGN KEY (released_by_id) REFERENCES users (id) ON DELETE SET NULL) %s', $id, $integer, $integer, $integer, $integer, $integer, $integer, $json, $datetime, $datetime, $datetime, $primaryKey, $suffix));
        $this->addSql('CREATE INDEX IDX_PROD_DATASHEET_DOC_BUILD ON production_datasheet_documents (build_instance_id)');
        $this->addSql('CREATE INDEX IDX_PROD_DATASHEET_DOC_TEMPLATE ON production_datasheet_documents (template_id)');
        $this->addSql('CREATE INDEX IDX_PROD_DATASHEET_DOC_REVISION ON production_datasheet_documents (revision_id)');
        $this->addSql('CREATE INDEX IDX_PROD_DATASHEET_DOC_USER ON production_datasheet_documents (released_by_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROD_DATASHEET_DOC_NUMBER ON production_datasheet_documents (build_instance_id, template_id, document_revision)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROD_DATASHEET_DOC_FILE ON production_datasheet_documents (stored_filename)');
    }

    private function dropTables(): void
    {
        $this->addSql('DROP TABLE production_datasheet_documents');
        $this->addSql('DROP TABLE production_datasheet_table_columns');
        $this->addSql('DROP TABLE production_datasheet_template_blocks');
        $this->addSql('DROP TABLE production_datasheet_template_revisions');
        $this->addSql('DROP TABLE production_datasheet_templates');
    }
}
