<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use App\Migration\AbstractMultiPlatformMigration;
use Doctrine\DBAL\Schema\Schema;

final class Version20260901200000 extends AbstractMultiPlatformMigration
{
    private const TABLE = 'production_customer_projects';
    private const LEGACY_INDEX = 'IDX_PROD_PROJECT_SITE';
    private const MAPPED_INDEX = 'IDX_4C1E9F4CE3A89B9B';

    public function getDescription(): string
    {
        return 'Normalize the production-site index name generated by Doctrine.';
    }

    public function mySQLUp(Schema $schema): void
    {
        if ($this->mustRenameIndex()) {
            $this->addSql(sprintf(
                'ALTER TABLE %s RENAME INDEX %s TO %s',
                self::TABLE,
                self::LEGACY_INDEX,
                self::MAPPED_INDEX,
            ));
        }
    }

    public function sqLiteUp(Schema $schema): void
    {
        if ($this->mustRenameIndex()) {
            $this->addSql(sprintf('DROP INDEX %s', self::LEGACY_INDEX));
            $this->addSql(sprintf(
                'CREATE INDEX %s ON %s (production_site_id)',
                self::MAPPED_INDEX,
                self::TABLE,
            ));
        }
    }

    public function postgreSQLUp(Schema $schema): void
    {
        if ($this->mustRenameIndex()) {
            $this->addSql(sprintf(
                'ALTER INDEX %s RENAME TO %s',
                self::LEGACY_INDEX,
                self::MAPPED_INDEX,
            ));
        }
    }

    public function mySQLDown(Schema $schema): void
    {
        // The change only normalizes metadata; keeping the mapped name is safe.
    }

    public function sqLiteDown(Schema $schema): void
    {
        // The change only normalizes metadata; keeping the mapped name is safe.
    }

    public function postgreSQLDown(Schema $schema): void
    {
        // The change only normalizes metadata; keeping the mapped name is safe.
    }

    private function mustRenameIndex(): bool
    {
        $legacyExists = false;
        $mappedExists = false;

        foreach ($this->connection->createSchemaManager()->listTableIndexes(self::TABLE) as $index) {
            $legacyExists = $legacyExists || 0 === strcasecmp($index->getName(), self::LEGACY_INDEX);
            $mappedExists = $mappedExists || 0 === strcasecmp($index->getName(), self::MAPPED_INDEX);
        }

        return $legacyExists && !$mappedExists;
    }
}
