<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use App\Migration\AbstractMultiPlatformMigration;
use Doctrine\DBAL\Schema\Schema;

final class Version20260903130000 extends AbstractMultiPlatformMigration
{
    public function getDescription(): string
    {
        return 'Add versioned production protocol templates, immutable numbered protocol runs, typed answers and build-instance attachments.';
    }

    public function mySQLUp(Schema $schema): void
    {
        $this->createTables('INT AUTO_INCREMENT NOT NULL', 'INT', 'TINYINT(1)', '1', '0', 'LONGTEXT', 'DATETIME', 'DATE', 'JSON', ', PRIMARY KEY(id)', 'DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
    }

    public function sqLiteUp(Schema $schema): void
    {
        $this->createTables('INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL', 'INTEGER', 'BOOLEAN', '1', '0', 'CLOB', 'DATETIME', 'DATE', 'CLOB', '', '');
    }

    public function postgreSQLUp(Schema $schema): void
    {
        $this->createTables('INT GENERATED BY DEFAULT AS IDENTITY NOT NULL', 'INT', 'BOOLEAN', 'TRUE', 'FALSE', 'TEXT', 'TIMESTAMP(0) WITHOUT TIME ZONE', 'DATE', 'JSON', ', PRIMARY KEY(id)', '');
    }

    public function mySQLDown(Schema $schema): void
    {
        $this->dropTables();
    }

    public function sqLiteDown(Schema $schema): void
    {
        $this->dropTables();
    }

    public function postgreSQLDown(Schema $schema): void
    {
        $this->dropTables();
    }

    private function createTables(string $id, string $integer, string $boolean, string $true, string $false, string $text, string $datetime, string $date, string $json, string $primaryKey, string $suffix): void
    {
        $this->addSql(sprintf('CREATE TABLE production_protocol_templates (id %s, name VARCHAR(255) NOT NULL, description %s NOT NULL, active %s DEFAULT %s NOT NULL, last_modified %s DEFAULT CURRENT_TIMESTAMP NOT NULL, datetime_added %s DEFAULT CURRENT_TIMESTAMP NOT NULL%s) %s', $id, $text, $boolean, $true, $datetime, $datetime, $primaryKey, $suffix));

        $this->addSql(sprintf('CREATE TABLE production_protocol_template_revisions (id %s, template_id %s NOT NULL, published_by_id %s DEFAULT NULL, revision_number %s NOT NULL, status VARCHAR(24) NOT NULL, change_note VARCHAR(255) DEFAULT NULL, published_at %s DEFAULT NULL, last_modified %s DEFAULT CURRENT_TIMESTAMP NOT NULL, datetime_added %s DEFAULT CURRENT_TIMESTAMP NOT NULL%s, CONSTRAINT FK_PROD_PROTOCOL_REV_TEMPLATE FOREIGN KEY (template_id) REFERENCES production_protocol_templates (id) ON DELETE CASCADE, CONSTRAINT FK_PROD_PROTOCOL_REV_USER FOREIGN KEY (published_by_id) REFERENCES users (id) ON DELETE SET NULL) %s', $id, $integer, $integer, $integer, $datetime, $datetime, $datetime, $primaryKey, $suffix));
        $this->addSql('CREATE INDEX IDX_PROD_PROTOCOL_REV_TEMPLATE ON production_protocol_template_revisions (template_id)');
        $this->addSql('CREATE INDEX IDX_PROD_PROTOCOL_REV_USER ON production_protocol_template_revisions (published_by_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROD_PROTOCOL_REVISION ON production_protocol_template_revisions (template_id, revision_number)');

        $this->addSql(sprintf('CREATE TABLE production_protocol_template_sections (id %s, revision_id %s NOT NULL, stable_key VARCHAR(36) NOT NULL, name VARCHAR(255) NOT NULL, description %s NOT NULL, position %s NOT NULL, repeatable %s DEFAULT %s NOT NULL, min_rows %s DEFAULT 1 NOT NULL, max_rows %s DEFAULT NULL, last_modified %s DEFAULT CURRENT_TIMESTAMP NOT NULL, datetime_added %s DEFAULT CURRENT_TIMESTAMP NOT NULL%s, CONSTRAINT FK_PROD_PROTOCOL_SECTION_REV FOREIGN KEY (revision_id) REFERENCES production_protocol_template_revisions (id) ON DELETE CASCADE) %s', $id, $integer, $text, $integer, $boolean, $false, $integer, $integer, $datetime, $datetime, $primaryKey, $suffix));
        $this->addSql('CREATE INDEX IDX_PROD_PROTOCOL_SECTION_REV ON production_protocol_template_sections (revision_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROD_PROTOCOL_SECTION_KEY ON production_protocol_template_sections (revision_id, stable_key)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROD_PROTOCOL_SECTION_POSITION ON production_protocol_template_sections (revision_id, position)');

        $this->addSql(sprintf('CREATE TABLE production_protocol_template_fields (id %s, section_id %s NOT NULL, stable_key VARCHAR(36) NOT NULL, label VARCHAR(255) NOT NULL, type VARCHAR(32) NOT NULL, unit VARCHAR(32) DEFAULT NULL, help_text %s DEFAULT NULL, position %s NOT NULL, required %s DEFAULT %s NOT NULL, options %s DEFAULT NULL, last_modified %s DEFAULT CURRENT_TIMESTAMP NOT NULL, datetime_added %s DEFAULT CURRENT_TIMESTAMP NOT NULL%s, CONSTRAINT FK_PROD_PROTOCOL_FIELD_SECTION FOREIGN KEY (section_id) REFERENCES production_protocol_template_sections (id) ON DELETE CASCADE) %s', $id, $integer, $text, $integer, $boolean, $false, $json, $datetime, $datetime, $primaryKey, $suffix));
        $this->addSql('CREATE INDEX IDX_PROD_PROTOCOL_FIELD_SECTION ON production_protocol_template_fields (section_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROD_PROTOCOL_FIELD_KEY ON production_protocol_template_fields (section_id, stable_key)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROD_PROTOCOL_FIELD_POSITION ON production_protocol_template_fields (section_id, position)');

        $this->addSql(sprintf('CREATE TABLE production_protocol_runs (id %s, build_instance_id %s NOT NULL, revision_id %s NOT NULL, started_by_id %s DEFAULT NULL, last_edited_by_id %s DEFAULT NULL, completed_by_id %s DEFAULT NULL, invalidated_by_id %s DEFAULT NULL, run_number %s NOT NULL, status VARCHAR(24) NOT NULL, completed_at %s DEFAULT NULL, invalidated_at %s DEFAULT NULL, invalid_reason %s DEFAULT NULL, last_modified %s DEFAULT CURRENT_TIMESTAMP NOT NULL, datetime_added %s DEFAULT CURRENT_TIMESTAMP NOT NULL%s, CONSTRAINT FK_PROD_PROTOCOL_RUN_BUILD FOREIGN KEY (build_instance_id) REFERENCES production_build_instances (id) ON DELETE CASCADE, CONSTRAINT FK_PROD_PROTOCOL_RUN_REV FOREIGN KEY (revision_id) REFERENCES production_protocol_template_revisions (id), CONSTRAINT FK_PROD_PROTOCOL_RUN_STARTED FOREIGN KEY (started_by_id) REFERENCES users (id) ON DELETE SET NULL, CONSTRAINT FK_PROD_PROTOCOL_RUN_EDITED FOREIGN KEY (last_edited_by_id) REFERENCES users (id) ON DELETE SET NULL, CONSTRAINT FK_PROD_PROTOCOL_RUN_COMPLETED FOREIGN KEY (completed_by_id) REFERENCES users (id) ON DELETE SET NULL, CONSTRAINT FK_PROD_PROTOCOL_RUN_INVALIDATED FOREIGN KEY (invalidated_by_id) REFERENCES users (id) ON DELETE SET NULL) %s', $id, $integer, $integer, $integer, $integer, $integer, $integer, $integer, $datetime, $datetime, $text, $datetime, $datetime, $primaryKey, $suffix));
        foreach ([
            'build_instance_id' => 'BUILD',
            'revision_id' => 'REV',
            'started_by_id' => 'STARTED',
            'last_edited_by_id' => 'EDITED',
            'completed_by_id' => 'COMPLETED',
            'invalidated_by_id' => 'INVALIDATED',
        ] as $column => $name) {
            $this->addSql(sprintf('CREATE INDEX IDX_PROD_PROTOCOL_RUN_%s ON production_protocol_runs (%s)', $name, $column));
        }
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROD_PROTOCOL_RUN_NUMBER ON production_protocol_runs (build_instance_id, run_number)');

        $this->addSql(sprintf('CREATE TABLE production_protocol_run_rows (id %s, run_id %s NOT NULL, section_id %s NOT NULL, sequence_number %s NOT NULL, last_modified %s DEFAULT CURRENT_TIMESTAMP NOT NULL, datetime_added %s DEFAULT CURRENT_TIMESTAMP NOT NULL%s, CONSTRAINT FK_PROD_PROTOCOL_ROW_RUN FOREIGN KEY (run_id) REFERENCES production_protocol_runs (id) ON DELETE CASCADE, CONSTRAINT FK_PROD_PROTOCOL_ROW_SECTION FOREIGN KEY (section_id) REFERENCES production_protocol_template_sections (id)) %s', $id, $integer, $integer, $integer, $datetime, $datetime, $primaryKey, $suffix));
        $this->addSql('CREATE INDEX IDX_PROD_PROTOCOL_ROW_RUN ON production_protocol_run_rows (run_id)');
        $this->addSql('CREATE INDEX IDX_PROD_PROTOCOL_ROW_SECTION ON production_protocol_run_rows (section_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROD_PROTOCOL_RUN_ROW ON production_protocol_run_rows (run_id, section_id, sequence_number)');

        $this->addSql(sprintf('CREATE TABLE production_protocol_answers (id %s, row_id %s NOT NULL, field_id %s NOT NULL, text_value %s DEFAULT NULL, integer_value %s DEFAULT NULL, decimal_value NUMERIC(24, 9) DEFAULT NULL, boolean_value %s DEFAULT NULL, date_value %s DEFAULT NULL, datetime_value %s DEFAULT NULL, last_modified %s DEFAULT CURRENT_TIMESTAMP NOT NULL, datetime_added %s DEFAULT CURRENT_TIMESTAMP NOT NULL%s, CONSTRAINT FK_PROD_PROTOCOL_ANSWER_ROW FOREIGN KEY (row_id) REFERENCES production_protocol_run_rows (id) ON DELETE CASCADE, CONSTRAINT FK_PROD_PROTOCOL_ANSWER_FIELD FOREIGN KEY (field_id) REFERENCES production_protocol_template_fields (id)) %s', $id, $integer, $integer, $text, $integer, $boolean, $date, $datetime, $datetime, $datetime, $primaryKey, $suffix));
        $this->addSql('CREATE INDEX IDX_PROD_PROTOCOL_ANSWER_ROW ON production_protocol_answers (row_id)');
        $this->addSql('CREATE INDEX IDX_PROD_PROTOCOL_ANSWER_FIELD ON production_protocol_answers (field_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROD_PROTOCOL_ANSWER ON production_protocol_answers (row_id, field_id)');

        $this->addSql(sprintf('CREATE TABLE production_build_instance_attachments (id %s, build_instance_id %s NOT NULL, uploaded_by_id %s DEFAULT NULL, original_filename VARCHAR(255) NOT NULL, stored_filename VARCHAR(255) NOT NULL, mime_type VARCHAR(255) NOT NULL, file_size %s NOT NULL, category VARCHAR(64) NOT NULL, sha256_checksum VARCHAR(64) NOT NULL, last_modified %s DEFAULT CURRENT_TIMESTAMP NOT NULL, datetime_added %s DEFAULT CURRENT_TIMESTAMP NOT NULL%s, CONSTRAINT FK_PROD_BUILD_ATTACHMENT_BUILD FOREIGN KEY (build_instance_id) REFERENCES production_build_instances (id) ON DELETE CASCADE, CONSTRAINT FK_PROD_BUILD_ATTACHMENT_USER FOREIGN KEY (uploaded_by_id) REFERENCES users (id) ON DELETE SET NULL) %s', $id, $integer, $integer, $integer, $datetime, $datetime, $primaryKey, $suffix));
        $this->addSql('CREATE INDEX IDX_PROD_BUILD_ATTACHMENT_BUILD ON production_build_instance_attachments (build_instance_id)');
        $this->addSql('CREATE INDEX IDX_PROD_BUILD_ATTACHMENT_USER ON production_build_instance_attachments (uploaded_by_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROD_BUILD_ATTACHMENT_FILE ON production_build_instance_attachments (stored_filename)');
    }

    private function dropTables(): void
    {
        $this->addSql('DROP TABLE production_protocol_answers');
        $this->addSql('DROP TABLE production_protocol_run_rows');
        $this->addSql('DROP TABLE production_protocol_runs');
        $this->addSql('DROP TABLE production_protocol_template_fields');
        $this->addSql('DROP TABLE production_protocol_template_sections');
        $this->addSql('DROP TABLE production_protocol_template_revisions');
        $this->addSql('DROP TABLE production_protocol_templates');
        $this->addSql('DROP TABLE production_build_instance_attachments');
    }
}
