<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use App\Migration\AbstractMultiPlatformMigration;
use Doctrine\DBAL\Schema\Schema;

final class Version20260821005000 extends AbstractMultiPlatformMigration
{
    public function getDescription(): string
    {
        return 'Add traceable project stock allocations backed by Part-DB part lots.';
    }

    public function mySQLUp(Schema $schema): void
    {
        $this->addSql('CREATE TABLE production_project_material_allocations (id INT AUTO_INCREMENT NOT NULL, customer_project_id INT NOT NULL, part_id INT NOT NULL, source_part_lot_id INT DEFAULT NULL, allocated_by_id INT DEFAULT NULL, quantity DOUBLE PRECISION NOT NULL, serial_number VARCHAR(128) DEFAULT NULL, last_modified DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, datetime_added DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX IDX_PROD_MATERIAL_PROJECT (customer_project_id), INDEX IDX_PROD_MATERIAL_PART (part_id), INDEX IDX_PROD_MATERIAL_LOT (source_part_lot_id), INDEX IDX_PROD_MATERIAL_USER (allocated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE production_project_material_allocations ADD CONSTRAINT FK_PROD_MATERIAL_PROJECT FOREIGN KEY (customer_project_id) REFERENCES production_customer_projects (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE production_project_material_allocations ADD CONSTRAINT FK_PROD_MATERIAL_PART FOREIGN KEY (part_id) REFERENCES parts (id)');
        $this->addSql('ALTER TABLE production_project_material_allocations ADD CONSTRAINT FK_PROD_MATERIAL_LOT FOREIGN KEY (source_part_lot_id) REFERENCES part_lots (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE production_project_material_allocations ADD CONSTRAINT FK_PROD_MATERIAL_USER FOREIGN KEY (allocated_by_id) REFERENCES users (id) ON DELETE SET NULL');
    }

    public function mySQLDown(Schema $schema): void
    {
        $this->addSql('DROP TABLE production_project_material_allocations');
    }

    public function sqLiteUp(Schema $schema): void
    {
        $this->addSql('CREATE TABLE production_project_material_allocations (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, customer_project_id INTEGER NOT NULL, part_id INTEGER NOT NULL, source_part_lot_id INTEGER DEFAULT NULL, allocated_by_id INTEGER DEFAULT NULL, quantity DOUBLE PRECISION NOT NULL, serial_number VARCHAR(128) DEFAULT NULL, last_modified DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, datetime_added DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT FK_PROD_MATERIAL_PROJECT FOREIGN KEY (customer_project_id) REFERENCES production_customer_projects (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_PROD_MATERIAL_PART FOREIGN KEY (part_id) REFERENCES parts (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_PROD_MATERIAL_LOT FOREIGN KEY (source_part_lot_id) REFERENCES part_lots (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_PROD_MATERIAL_USER FOREIGN KEY (allocated_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_PROD_MATERIAL_PROJECT ON production_project_material_allocations (customer_project_id)');
        $this->addSql('CREATE INDEX IDX_PROD_MATERIAL_PART ON production_project_material_allocations (part_id)');
        $this->addSql('CREATE INDEX IDX_PROD_MATERIAL_LOT ON production_project_material_allocations (source_part_lot_id)');
        $this->addSql('CREATE INDEX IDX_PROD_MATERIAL_USER ON production_project_material_allocations (allocated_by_id)');
    }

    public function sqLiteDown(Schema $schema): void
    {
        $this->addSql('DROP TABLE production_project_material_allocations');
    }

    public function postgreSQLUp(Schema $schema): void
    {
        $this->addSql('CREATE TABLE production_project_material_allocations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, customer_project_id INT NOT NULL, part_id INT NOT NULL, source_part_lot_id INT DEFAULT NULL, allocated_by_id INT DEFAULT NULL, quantity DOUBLE PRECISION NOT NULL, serial_number VARCHAR(128) DEFAULT NULL, last_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, datetime_added TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_PROD_MATERIAL_PROJECT ON production_project_material_allocations (customer_project_id)');
        $this->addSql('CREATE INDEX IDX_PROD_MATERIAL_PART ON production_project_material_allocations (part_id)');
        $this->addSql('CREATE INDEX IDX_PROD_MATERIAL_LOT ON production_project_material_allocations (source_part_lot_id)');
        $this->addSql('CREATE INDEX IDX_PROD_MATERIAL_USER ON production_project_material_allocations (allocated_by_id)');
        $this->addSql('ALTER TABLE production_project_material_allocations ADD CONSTRAINT FK_PROD_MATERIAL_PROJECT FOREIGN KEY (customer_project_id) REFERENCES production_customer_projects (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE production_project_material_allocations ADD CONSTRAINT FK_PROD_MATERIAL_PART FOREIGN KEY (part_id) REFERENCES parts (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE production_project_material_allocations ADD CONSTRAINT FK_PROD_MATERIAL_LOT FOREIGN KEY (source_part_lot_id) REFERENCES part_lots (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE production_project_material_allocations ADD CONSTRAINT FK_PROD_MATERIAL_USER FOREIGN KEY (allocated_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function postgreSQLDown(Schema $schema): void
    {
        $this->addSql('DROP TABLE production_project_material_allocations');
    }
}
